# Generated by Django 5.1.4 on 2025-10-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default='2025-10-21'),
            preserve_default=False,
        ),
    ]
