# Generated by Django 5.1.4 on 2025-10-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='month',
            field=models.CharField(choices=[('1', 'Вересень'), ('2', 'Жовтень'), ('3', 'Листопад'), ('4', 'Грудень')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
