# Generated by Django 5.1.4 on 2025-11-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_post_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('0', 'Без категорії'), ('1', 'Олімпіади'), ('2', 'Конкурси'), ('3', '--------')], default=0, max_length=32),
            preserve_default=False,
        ),
    ]
