# Generated by Django 5.1.4 on 2025-12-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pict', models.ImageField(blank=True, upload_to='picts/')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='pict',
        ),
        migrations.AddField(
            model_name='post',
            name='pict',
            field=models.ManyToManyField(to='school_app.picture'),
        ),
    ]
