# Generated by Django 5.1.4 on 2025-12-11 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_picture_remove_post_pict_post_pict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pict',
        ),
        migrations.AddField(
            model_name='picture',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='school_app.post'),
            preserve_default=False,
        ),
    ]
